# Generated by Django 3.2.4 on 2021-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210616_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
